# Generated by Django 5.1.3 on 2024-12-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeruser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="customeruser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
